version: '3'

services:
  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: scheduler
    restart: always
    environment:
      - SERVER_PORT=8080
      - REDIS_URL=redis://redis:6379
    ports:
      - '8080:8080' 
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: always
    container_name: redis
    ports:
    - "6379:6379"