version: '3'

services:
  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: scheduler
    restart: always
    environment:
      - SERVER_PORT=8080
      - MONGO_URL=mongo://mongo:27017
    ports:
      - '8080:8080' 
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - '27017:27017'